### ISSUE TITLE
go get URL wrong on README

### ISSUE THREAD

**Issue by joaoh82** [rafaeljesus/nsq-event-bus#13]
When using the example from README to get the package, we get this error:
```
go get -u https://github.com/rafaeljesus/nsq-event-bus
package https:/github.com/rafaeljesus/nsq-event-bus: "https://" not allowed in import path
```

There is no need for the https in the go get... ;)

**Comment by rafaeljesus** [comment]
@joaoh82 thx mate for using the package. I will fix this as soon as I can, or you can submit a PR that I merge it if you really need it asap 😃
